### ISSUE TITLE
invalid memory address or nil pointer dereference in message.go:30

### ISSUE THREAD

**Issue by Fank** [redis/rueidis#229]
Issue during connection with redis directly.
```
2023/05/12 22:52:53 http: panic serving [::1]:59594: runtime error: invalid memory address or nil pointer dereference
goroutine 949 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x3515200, 0x705fbd0})
        /usr/local/go/src/runtime/panic.go:890 +0x263
...
panic({0x3515200, 0x705fbd0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/redis/rueidis.(*RedisError).Error(0x7077840?)
        /home/fank/go/pkg/mod/github.com/redis/rueidis@v1.0.2/message.go:30
gitlab.com/mcldev/negsoft/api/src/middleware.AuthorizationHandler.func1.1(0xc00234a900, {0x45afa90, 0xc003c161c0}, 0xc001643780)
...
```

https://github.com/redis/rueidis/blob/v1.0.2/message.go#L30 affected line.

Here a cut from how the calls to redis looks like:
```go
	permissions := []string{"foo", "bar"}
	fieldValue := redisClient.B().Hmset().Key(key).FieldValue()
	for _, v := range permissions {
		fieldValue = fieldValue.FieldValue(v, "1")
	}

	response = redisClient.DoMulti(ctx, fieldValue.Build(), redisClient.B().Expire().Key(key).Seconds(12*60*60).Build())
	for i, v := range response {
		err = v.RedisError()
		fmt.Println(i, err)
		fmt.Printf("%#v", err)
		if err == nil {
			fmt.Println("11111")
		}
		if err != nil {
			return false, err
		}

		fmt.Println("asd")
	}
```

the part of how i test it.
```go
client.EXPECT().DoMulti(ctx, mock.Match("HMSET", "core:user:permission:123", "view_posts", "1"), mock.Match("EXPIRE", "core:user:permission:123", "43200")).Return([]rueidis.RedisResult{
    mock.Result(mock.RedisString("OK")),
    mock.Result(mock.RedisInt64(1)),
})
```

the debug output in the tests:
```
=== RUN   TestGuard_CanAccessAny
--- FAIL: TestGuard_CanAccessAny (0.00s)
=== RUN   TestGuard_CanAccessAny/key_miss
    --- FAIL: TestGuard_CanAccessAny/key_miss (0.00s)
=== RUN   TestGuard_CanAccessAny/key_miss/permission_miss
        --- FAIL: TestGuard_CanAccessAny/key_miss/permission_miss (0.00s)
=== RUN   TestGuard_CanAccessAny/key_miss/permission_miss/loader_single
0 <nil>
(*rueidis.RedisError)(nil)    guard_test.go:165: 
        	Error Trace:	C:/Users/info/repo/api/src/negsoft/user_permission/guard_test.go:165
        	Error:      	Received unexpected error:
        	            	<nil>
        	Test:       	TestGuard_CanAccessAny/key_miss/permission_miss/loader_single
            --- FAIL: TestGuard_CanAccessAny/key_miss/permission_miss/loader_single (0.00s)
```

Looks like it doesn't like the combination of HMSET and EXPIRE in a DoMulti, but its just a guess still investigating.

**Comment by Fank** [comment]
Environment:
```
$ docker exec -it redis-1 redis-cli --version
redis-cli 7.0.11
$ go version
go version go1.20 linux/amd64
```

**Comment by Fank** [comment]
It looks like the `DoMulti` did its job without issues:
```
127.0.0.1:6379[1]> HGET core:user:permission:577 test
"1"
127.0.0.1:6379[1]> TTL core:user:permission:577
(integer) 42079
```
i have the fields and the ttl from the expire.

**Comment by Fank** [comment]
i have the feeling it comes from the 2. `DoMulti` at the end of `CanAccessAny`.
Code linked below, make testing easier.

<details>
  <summary>guard.go</summary>
  
```go
package user_permission

import (
	"context"
	"errors"
	"fmt"

	"github.com/redis/rueidis"
)

const (
	redisPrefix = "core:user:permission"
)

type Guard struct {
	redisClient rueidis.Client
	loader      Loader
}

type Loader func(ctx context.Context, userID int) ([]string, error)

func NewGuard(redisClient rueidis.Client, loader Loader) *Guard {
	return &Guard{
		redisClient: redisClient,
		loader:      loader,
	}
}

func (g *Guard) CanAccessAny(ctx context.Context, userID int, permissionNames ...string) (bool, error) {
	if len(permissionNames) == 0 {
		return false, errors.New("no permission names provided")
	}

	key := fmt.Sprintf("%s:%d", redisPrefix, userID)

	response := g.redisClient.DoMulti(
		ctx,
		g.redisClient.B().Exists().Key(key).Build(),
		g.redisClient.B().Hmget().Key(key).Field(permissionNames...).Build(),
	)

	keyExists, err := response[0].ToInt64()
	if err != nil && !errors.Is(err, rueidis.Nil) {
		return false, err
	}

	if keyExists > 0 {
		permissions, err := response[1].ToArray()
		if err != nil {
			return false, err
		}

		for _, v := range permissions {
			value, err := v.ToString()
			if errors.Is(err, rueidis.Nil) {
				continue
			} else if err != nil {
				return false, err
			}

			if value == "1" {
				return true, nil
			}
		}

		// no permissions, but key exists so -> no access.
		return false, nil
	}

	permissions, err := g.loader(ctx, userID)
	if err != nil {
		return false, err
	}

	// there are no permissions for this userID.
	if len(permissions) == 0 {
		return false, nil
	}

	fieldValue := g.redisClient.B().Hmset().Key(key).FieldValue()
	for _, v := range permissions {
		fieldValue = fieldValue.FieldValue(v, "1")
	}

	response = g.redisClient.DoMulti(ctx, fieldValue.Build(), g.redisClient.B().Expire().Key(key).Seconds(12*60*60).Build())
	for i, v := range response {
		err = v.RedisError()
		fmt.Println(i, err)
		fmt.Printf("%#v", err)
		if err == nil {
			fmt.Println("11111")
		}
		if err != nil {
			return false, err
		}

		fmt.Println("asd")
	}

	return false, nil
}

```
</details>

<details>
  <summary>guard_test.go</summary>
  
```go
package user_permission

import (
	"context"
	"errors"
	"testing"

	"github.com/golang/mock/gomock"
	"github.com/redis/rueidis"
	"github.com/redis/rueidis/mock"
	"github.com/stretchr/testify/assert"
)

func TestGuard_CanAccessAny(t *testing.T) {
	t.Run("empty", func(t *testing.T) {
		ctrl := gomock.NewController(t)
		defer ctrl.Finish()

		ctx := context.Background()
		client := mock.NewClient(ctrl)

		val, err := NewGuard(client, nil).CanAccessAny(ctx, 0)
		assert.ErrorContainsf(t, err, "permission", "")
		assert.Equal(t, false, val)
	})
	t.Run("key error", func(t *testing.T) {
		ctrl := gomock.NewController(t)
		defer ctrl.Finish()

		ctx := context.Background()
		client := mock.NewClient(ctrl)

		client.EXPECT().DoMulti(ctx, mock.Match("EXISTS", "core:user:permission:123"), mock.Match("HMGET", "core:user:permission:123", "asd")).Return([]rueidis.RedisResult{
			mock.ErrorResult(rueidis.ErrClosing),
			mock.ErrorResult(rueidis.ErrNoAddr),
		})

		val, err := NewGuard(client, nil).CanAccessAny(ctx, 123, "asd")
		assert.ErrorIs(t, rueidis.ErrClosing, err)
		assert.Equal(t, false, val)

	})
	t.Run("key hit", func(t *testing.T) {
		t.Run("permission miss", func(t *testing.T) {
			ctrl := gomock.NewController(t)
			defer ctrl.Finish()

			ctx := context.Background()
			client := mock.NewClient(ctrl)

			client.EXPECT().DoMulti(ctx, mock.Match("EXISTS", "core:user:permission:123"), mock.Match("HMGET", "core:user:permission:123", "asd")).Return([]rueidis.RedisResult{
				mock.Result(mock.RedisInt64(1)),
				mock.Result(mock.RedisArray(mock.RedisNil())),
			})

			val, err := NewGuard(client, nil).CanAccessAny(ctx, 123, "asd")
			assert.NoError(t, err)
			assert.Equal(t, false, val)
		})
		t.Run("permission miss hit", func(t *testing.T) {
			ctrl := gomock.NewController(t)
			defer ctrl.Finish()

			ctx := context.Background()
			client := mock.NewClient(ctrl)

			client.EXPECT().DoMulti(ctx, mock.Match("EXISTS", "core:user:permission:123"), mock.Match("HMGET", "core:user:permission:123", "asd", "def")).Return([]rueidis.RedisResult{
				mock.Result(mock.RedisInt64(1)),
				mock.Result(mock.RedisArray(mock.RedisNil(), mock.RedisString("1"))),
			})

			val, err := NewGuard(client, nil).CanAccessAny(ctx, 123, "asd", "def")
			assert.NoError(t, err)
			assert.Equal(t, true, val)
		})
		t.Run("permission miss error", func(t *testing.T) {
			ctrl := gomock.NewController(t)
			defer ctrl.Finish()

			ctx := context.Background()
			client := mock.NewClient(ctrl)

			client.EXPECT().DoMulti(ctx, mock.Match("EXISTS", "core:user:permission:123"), mock.Match("HMGET", "core:user:permission:123", "asd", "def")).Return([]rueidis.RedisResult{
				mock.Result(mock.RedisInt64(1)),
				mock.Result(mock.RedisArray(mock.RedisNil(), mock.RedisError("something"))),
			})

			val, err := NewGuard(client, nil).CanAccessAny(ctx, 123, "asd", "def")
			assert.ErrorContains(t, err, "something")
			assert.Equal(t, false, val)
		})
		t.Run("permission error", func(t *testing.T) {
			ctrl := gomock.NewController(t)
			defer ctrl.Finish()

			ctx := context.Background()
			client := mock.NewClient(ctrl)

			client.EXPECT().DoMulti(ctx, mock.Match("EXISTS", "core:user:permission:123"), mock.Match("HMGET", "core:user:permission:123", "asd")).Return([]rueidis.RedisResult{
				mock.Result(mock.RedisInt64(1)),
				mock.ErrorResult(rueidis.ErrClosing),
			})

			val, err := NewGuard(client, nil).CanAccessAny(ctx, 123, "asd")
			assert.ErrorIs(t, rueidis.ErrClosing, err)
			assert.Equal(t, false, val)
		})
	})
	t.Run("key miss", func(t *testing.T) {
		t.Run("permission miss loader error", func(t *testing.T) {
			ctrl := gomock.NewController(t)
			defer ctrl.Finish()

			ctx := context.Background()
			client := mock.NewClient(ctrl)

			client.EXPECT().DoMulti(ctx, mock.Match("EXISTS", "core:user:permission:123"), mock.Match("HMGET", "core:user:permission:123", "asd")).Return([]rueidis.RedisResult{
				mock.Result(mock.RedisNil()),
				mock.Result(mock.RedisNil()),
			})

			val, err := NewGuard(client, func(ctx context.Context, userID int) ([]string, error) {
				return nil, errors.New("loader error")
			}).CanAccessAny(ctx, 123, "asd")
			assert.ErrorContains(t, err, "loader error")
			assert.Equal(t, false, val)
		})
		t.Run("permission miss", func(t *testing.T) {
			t.Run("loader empty", func(t *testing.T) {
				ctrl := gomock.NewController(t)
				defer ctrl.Finish()

				ctx := context.Background()
				client := mock.NewClient(ctrl)

				client.EXPECT().DoMulti(ctx, mock.Match("EXISTS", "core:user:permission:123"), mock.Match("HMGET", "core:user:permission:123", "asd")).Return([]rueidis.RedisResult{
					mock.Result(mock.RedisNil()),
					mock.Result(mock.RedisNil()),
				})

				val, err := NewGuard(client, func(ctx context.Context, userID int) ([]string, error) {
					return []string{}, nil
				}).CanAccessAny(ctx, 123, "asd")
				assert.NoError(t, err)
				assert.Equal(t, false, val)
			})
			t.Run("loader single", func(t *testing.T) {
				ctrl := gomock.NewController(t)
				defer ctrl.Finish()

				ctx := context.Background()
				client := mock.NewClient(ctrl)

				client.EXPECT().DoMulti(ctx, mock.Match("EXISTS", "core:user:permission:123"), mock.Match("HMGET", "core:user:permission:123", "asd")).Return([]rueidis.RedisResult{
					mock.Result(mock.RedisNil()),
					mock.Result(mock.RedisNil()),
				})
				client.EXPECT().DoMulti(ctx, mock.Match("EXPIRE", "core:user:permission:123", "43200")).Return([]rueidis.RedisResult{
					mock.Result(mock.RedisString("OK")),
					mock.Result(mock.RedisInt64(1)),
				})

				val, err := NewGuard(client, func(ctx context.Context, userID int) ([]string, error) {
					return []string{"view_posts"}, nil
				}).CanAccessAny(ctx, 123, "asd")
				assert.NoError(t, err)
				assert.Equal(t, false, val)
			})
		})
	})
}
```
</details>

**Comment by rueian** [comment]
Hi @Fank,

Thank you for reporting this. This can be considered a nil dereference bug when combining `err := v.RedisError()` and `err.Error()`. We can fix this soon.

On the other hand, `v.RedissError()` only returns concrete err value when the response is a Redis ERR message. It is better to use `v.Error()` instead, which will also return other errors, such as networking errors.

**Comment by rueian** [comment]
Hi @Fank,

We are going to replace `v.RedisError()` with `rueidis.IsRedisErr(v.Error())` in the next version https://github.com/redis/rueidis/pull/230.

Would you happen to have any concerns about it?

**Comment by Fank** [comment]
Thanks for the change in #230.
For what ever reason i didn't noticed there is `v.Error()`.
Personally i like this kind of change because its similar to how `errors.As()` works.
