### ISSUE TITLE
NewClient() hangs

### ISSUE THREAD

**Issue by jdemeyer** [redis/rueidis#237]
As the title says, `NewClient()` just hangs for me and there doesn't seem to be a way to set a timeout or context for `NewClient()`.

I've set up a basic redis cluster with docker-compose. It's likely that I misconfigured this docker-compose setup, still that shouldn't cause `NewClient()` to hang.

I'm using this `ClientOption`:
```
    cfg := rueidis.ClientOption{
        InitAddress: []string{"172.31.0.2:6379", "172.31.0.3:6379", "172.31.0.4:6379"},
        ShuffleInit: true,
        Dialer: net.Dialer{
            Timeout: 5*time.Second,
            KeepAlive: 10*time.Second,
        },
        ConnWriteTimeout: 10 * time.Second,
    }
```
As you can see, I think I set all timeouts that I could (or am I missing something?).  I've tested that `NewClient()` correctly times out if it can't connect at all (if redis cluster simply isn't running). So in this case, it is connecting but then it hangs somehow.

I pasted my `panic` log below. I think it's stuck in the retry loop in `rueidis.clusterClient._refresh()`.

The `[REDACTED]` is my user code, but that's just a `rueidis.NewClient(cfg)` call with the config I pasted above.
```
panic: test timed out after 1m0s
running tests:
        TestRedis (58s)

goroutine 420051 [running]:
testing.(*M).startAlarm.func1()
        /usr/lib/go/src/testing/testing.go:2241 +0x3b9
created by time.goFunc
        /usr/lib/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000702340, {0x138a116?, 0x528645?}, 0x13eba50)
        /usr/lib/go/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x1f39940?)
        /usr/lib/go/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc000702340, 0xc00060fc88)
        /usr/lib/go/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0000b4640?, {0x1f2b1c0, 0x4, 0x4}, {0x20?, 0x100c0000ca9e8?, 0x1f38f20?})
        /usr/lib/go/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0000b4640)
        /usr/lib/go/src/testing/testing.go:1906 +0x63a
main.main()
        _testmain.go:53 +0x1aa

goroutine 371 [chan receive]:
github.com/redis/rueidis.(*clusterClient).init(0xc000980000)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:75 +0x267
github.com/redis/rueidis.(*clusterClient)._refresh(0xc000980000)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:110 +0x1cb
github.com/redis/rueidis.(*call).Do(0xc0009c0018, 0xc0000898e0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/singleflight.go:26 +0x10f
github.com/redis/rueidis.(*clusterClient).refresh(...)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:85
github.com/redis/rueidis.newClusterClient(0xc000226600, 0x13ec970)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:44 +0xfa
github.com/redis/rueidis.NewClient({{0x12a05f200, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x2540be400, 0x0, ...}, ...})
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/rueidis.go:282 +0x149
[REDACTED]

goroutine 163 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0006642d0)
        /home/jdemeyer/go/pkg/mod/google.golang.org/grpc@v1.45.0/balancer_conn_wrappers.go:77 +0xa5
created by google.golang.org/grpc.newCCBalancerWrapper
        /home/jdemeyer/go/pkg/mod/google.golang.org/grpc@v1.45.0/balancer_conn_wrappers.go:67 +0x245

goroutine 419966 [runnable]:
syscall.Syscall(0x7fd844314408?, 0x0?, 0x4a79d2?, 0x7ffff800000?)
        /usr/lib/go/src/syscall/syscall_linux.go:69 +0x27
syscall.read(0xc0000b8380?, {0xc0017d6000?, 0xc00088d800?, 0x40f25e?})
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:711 +0x45
syscall.Read(...)
        /usr/lib/go/src/syscall/syscall_unix.go:178
internal/poll.ignoringEINTRIO(...)
        /usr/lib/go/src/internal/poll/fd_unix.go:794
internal/poll.(*FD).Read(0xc0000b8380?, {0xc0017d6000?, 0x80000?, 0x80000?})
        /usr/lib/go/src/internal/poll/fd_unix.go:163 +0x2ce
net.(*netFD).Read(0xc0000b8380, {0xc0017d6000?, 0x53051c?, 0x0?})
        /usr/lib/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc0004b2008, {0xc0017d6000?, 0x0?, 0x0?})
        /usr/lib/go/src/net/net.go:183 +0x45
bufio.(*Reader).fill(0xc000902000)
        /usr/lib/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).ReadByte(0xc000902000)
        /usr/lib/go/src/bufio/bufio.go:265 +0x2c
github.com/redis/rueidis.readNextMessage(0x1f68af0?)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/resp.go:217 +0x8f
github.com/redis/rueidis.(*pipe)._backgroundRead(0xc00046b320)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:362 +0x1bf
github.com/redis/rueidis.(*pipe)._background(0xc00046b320)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:232 +0x7e
created by github.com/redis/rueidis.(*pipe).background.func1
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:216 +0x5a

goroutine 27 [IO wait]:
internal/poll.runtime_pollWait(0x7fd844d45d08, 0x72)
        /usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00016e280?, 0xc0004f4000?, 0x0)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00016e280, {0xc0004f4000, 0x8000, 0x8000})
        /usr/lib/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc00016e280, {0xc0004f4000?, 0x1060100000000?, 0x8?})
        /usr/lib/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000014020, {0xc0004f4000?, 0x8d395b?, 0xc0006221c8?})
        /usr/lib/go/src/net/net.go:183 +0x45
bufio.(*Reader).Read(0xc0000a0180, {0xc00015e040, 0x9, 0x7fd86d0b4f18?})
        /usr/lib/go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x164d980, 0xc0000a0180}, {0xc00015e040, 0x9, 0x9}, 0x9)
        /usr/lib/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
        /usr/lib/go/src/io/io.go:351
golang.org/x/net/http2.readFrameHeader({0xc00015e040?, 0x9?, 0x4fd206bf?}, {0x164d980?, 0xc0000a0180?})
        /home/jdemeyer/go/pkg/mod/golang.org/x/net@v0.8.0/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00015e000)
        /home/jdemeyer/go/pkg/mod/golang.org/x/net@v0.8.0/http2/frame.go:498 +0x95
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc00021c1e0)
        /home/jdemeyer/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_client.go:1499 +0x45e
created by google.golang.org/grpc/internal/transport.newHTTP2Client
        /home/jdemeyer/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_client.go:364 +0x1a1f

goroutine 28 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc000136550, 0x1)
        /home/jdemeyer/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/controlbuf.go:407 +0x115
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0000a01e0)
        /home/jdemeyer/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/controlbuf.go:534 +0x85
google.golang.org/grpc/internal/transport.newHTTP2Client.func3()
        /home/jdemeyer/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_client.go:414 +0x6a
created by google.golang.org/grpc/internal/transport.newHTTP2Client
        /home/jdemeyer/go/pkg/mod/google.golang.org/grpc@v1.45.0/internal/transport/http2_client.go:412 +0x1fb1

goroutine 49 [IO wait]:
internal/poll.runtime_pollWait(0x7fd844d45df8, 0x72)
        /usr/lib/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0000b8f00?, 0xc000859000?, 0x0)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0000b8f00, {0xc000859000, 0x1000, 0x1000})
        /usr/lib/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc0000b8f00, {0xc000859000?, 0x43be27?, 0xc000621c30?})
        /usr/lib/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000510500, {0xc000859000?, 0x0?, 0xc0007036c0?})
        /usr/lib/go/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc000839560, {0xc000859000?, 0xc00003c240?, 0xc000621d30?})
        /usr/lib/go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc0000a0840)
        /usr/lib/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc0000a0840, 0x1)
        /usr/lib/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc000839560)
        /usr/lib/go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:1765 +0x16ea

goroutine 306 [select]:
net/http.(*persistConn).writeLoop(0xc000839560)
        /usr/lib/go/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:1766 +0x173d

goroutine 387 [select]:
github.com/redis/rueidis.(*pipe).backgroundPing(0xc0003d37a0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:478 +0x105
created by github.com/redis/rueidis._newPipe
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:209 +0x1b2d

goroutine 420039 [runnable]:
github.com/redis/rueidis.newRing(0xc0007299a0?)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/ring.go:28 +0x1d9
github.com/redis/rueidis._newPipe(0xc0005b8360, 0xc000226600, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:82 +0xae
github.com/redis/rueidis.newPipe(...)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:72
github.com/redis/rueidis.makeMux.func1()
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:56 +0xc6
github.com/redis/rueidis.(*mux)._pipe(0xc00073b290, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:113 +0x309
github.com/redis/rueidis.(*mux).Dial(0xc000136870?)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:145 +0x1b
github.com/redis/rueidis.(*clusterClient).init.func1({0x138fbd6, 0xf}, {0x165d980, 0xc00073b290})
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:59 +0x48
created by github.com/redis/rueidis.(*clusterClient).init
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:58 +0x9d

goroutine 420040 [runnable]:
github.com/redis/rueidis.newRing(0xc0005679a0?)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/ring.go:25 +0xda
github.com/redis/rueidis._newPipe(0xc0004c6f90, 0xc000226600, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:82 +0xae
github.com/redis/rueidis.newPipe(...)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:72
github.com/redis/rueidis.makeMux.func1()
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:56 +0xc6
github.com/redis/rueidis.(*mux)._pipe(0xc00073b320, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:113 +0x309
github.com/redis/rueidis.(*mux).Dial(0x3?)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:145 +0x1b
github.com/redis/rueidis.(*clusterClient).init.func1({0x138fbc7, 0xf}, {0x165d980, 0xc00073b320})
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:59 +0x48
created by github.com/redis/rueidis.(*clusterClient).init
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:58 +0x9d

goroutine 376 [select]:
github.com/redis/rueidis.(*pipe).backgroundPing(0xc000838000)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:478 +0x105
created by github.com/redis/rueidis._newPipe
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:209 +0x1b2d

goroutine 419967 [runnable]:
runtime.Gosched(...)
        /usr/lib/go/src/runtime/proc.go:321
github.com/redis/rueidis.(*pipe)._backgroundWrite(0xc00046b320)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:330 +0x4a5
github.com/redis/rueidis.(*pipe)._background.func1()
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:228 +0x25
created by github.com/redis/rueidis.(*pipe)._background
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:227 +0x71

goroutine 305 [select]:
github.com/redis/rueidis.(*pipe).backgroundPing(0xc00077e120)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:478 +0x105
created by github.com/redis/rueidis._newPipe
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:209 +0x1b2d

goroutine 419965 [runnable]:
github.com/redis/rueidis.(*pipe).Close(0xc00046b320)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:1186 +0x105
github.com/redis/rueidis.(*mux).Close(0xc00073a1b0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:307 +0xf9
created by github.com/redis/rueidis.(*clusterClient).init.func1
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:62 +0xf9

goroutine 419964 [select]:
github.com/redis/rueidis.(*pipe).backgroundPing(0xc00046b320)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:478 +0x105
created by github.com/redis/rueidis._newPipe
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:209 +0x1b2d

goroutine 420038 [runnable]:
sync.NewCond(...)
        /usr/lib/go/src/sync/cond.go:48
github.com/redis/rueidis.newRing(0x0?)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/ring.go:27 +0x15e
github.com/redis/rueidis._newPipe(0xc000598360, 0xc000226600, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:82 +0xae
github.com/redis/rueidis.newPipe(...)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/pipe.go:72
github.com/redis/rueidis.makeMux.func1()
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:56 +0xc6
github.com/redis/rueidis.(*mux)._pipe(0xc00073a3f0, 0x0)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:113 +0x309
github.com/redis/rueidis.(*mux).Dial(0xc0004ac4e0?)
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/mux.go:145 +0x1b
github.com/redis/rueidis.(*clusterClient).init.func1({0x138fbb8, 0xf}, {0x165d980, 0xc00073a3f0})
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:59 +0x48
created by github.com/redis/rueidis.(*clusterClient).init
        /home/jdemeyer/go/pkg/mod/github.com/redis/rueidis@v1.0.3/cluster.go:58 +0x9d
exit status 2
```

**Comment by rueian** [comment]
Hi @jdemeyer,

Thank you for your detailed report.

Sure that the NewClient should be improved to respect timeout settings.

Based on your description, I think you might be trapped in the common mistake while setting up a testing redis cluster with docker that redis nodes report internal IPs to the client and it can’t connect to them through internal IPs.

Would you like to try to setup a cluster in this way?
https://github.com/redis/rueidis/blob/e947cdaf934d1faa82fea0b7ff988ab92c652808/docker-compose.yml#L64-L74

**Comment by rueian** [comment]
After digging deeper, I think it might be because your cluster didn't have slots allocated.
Off course the NewClient should be modified to take this case into count.

**Comment by rueian** [comment]
Hi @jdemeyer, have you still faced the issue? Is it because your cluster has no slots?

**Comment by rueian** [comment]
I’ll recommend you to try the latest v1.0.4.
