### ISSUE TITLE
Panic using `HSet()` to store a struct with `rueidiscompat.Compat`

### ISSUE THREAD

**Issue by mbrancato** [redis/rueidis#307]
I receive a panic using `HSet()` to store a struct as I would using `go-redis`.

```
=== RUN   TestRueidisCompatHSet
--- FAIL: TestRueidisCompatHSet (5.98s)
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 18 [running]:
testing.tRunner.func1.2({0x1966d60, 0xc0000a8570})
	/Users/mike/go/go1.20.5/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/Users/mike/go/go1.20.5/src/testing/testing.go:1529 +0x39f
panic({0x1966d60, 0xc0000a8570})
	/Users/mike/go/go1.20.5/src/runtime/panic.go:884 +0x213
github.com/redis/rueidis/rueidiscompat.(*Compat).HSet(0xc00057fd30, {0x1ac7c40, 0xc000287e60}, {0x19cb01b, 0x4}, {0xc00057fd20, 0x1, 0x1})
	/Users/mike/go/pkg/mod/github.com/redis/rueidis@v1.0.12/rueidiscompat/adapter.go:1126 +0x306
...
```

I've created a minimal test below:
```golang
package tests

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/ory/dockertest/v3"
	"github.com/redis/go-redis/v9"
	"github.com/redis/rueidis"
	"github.com/redis/rueidis/rueidiscompat"
)

type Foo struct {
	Bar bool `redis:"bar"`
}

func TestGoRedisHSet(t *testing.T) {
	teardown, addr := setupTestRedis(t)
	defer teardown()
	time.Sleep(5 * time.Second)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	rdb := redis.NewClient(
		&redis.Options{Addr: addr},
	)

	rdb.HSet(ctx, "test", &Foo{Bar: true})
}

func TestRueidisCompatHSet(t *testing.T) {
	teardown, addr := setupTestRedis(t)
	defer teardown()
	time.Sleep(5 * time.Second)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	rc, err := rueidis.NewClient(
		rueidis.ClientOption{
			InitAddress: []string{addr},
		},
	)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	rdb := rueidiscompat.NewAdapter(rc)

	rdb.HSet(ctx, "test", &Foo{Bar: true})
}

func setupTestRedis(t testing.TB) (func(), string) {
	pool, err := dockertest.NewPool("")
	if err != nil {
		t.Fatalf("could not construct pool: %s", err)
	}

	err = pool.Client.Ping()
	if err != nil {
		t.Fatalf("could not connect to Docker: %s", err)
	}

	resource, _ := pool.ContainerByName("test-redis")
	if resource != nil {
		_ = pool.Purge(resource)
	}

	resource, err = pool.RunWithOptions(
		&dockertest.RunOptions{
			Name:       "test-redis",
			Repository: "redis",
		},
	)
	if err != nil {
		if resource != nil {
			_ = pool.Purge(resource)
		}
		t.Fatalf("could not start resource: %s", err)
	}

	var rdb *redis.Client
	rdbPort := resource.GetPort("6379/tcp")
	err = pool.Retry(
		func() error {
			ctx, cancel := context.WithTimeout(context.Background(), time.Duration(10*time.Second))
			defer cancel()
			rdb = redis.NewClient(
				&redis.Options{
					Addr: fmt.Sprintf(":%v", rdbPort),
				},
			)
			v := rdb.Info(ctx)
			if v.String() != "" {
				return nil
			}
			return fmt.Errorf("error connecting to redis")
		},
	)
	if err != nil {
		if resource != nil {
			_ = pool.Purge(resource)
		}
		t.Fatalf("could not connect to database: %s", err)
	}

	teardown := func() {
		err = pool.Purge(resource)
		if err != nil {
			t.Fatalf("error removing database container: %s", err)
		}
	}

	dsn := fmt.Sprintf(":%v", rdbPort)

	return teardown, dsn
}

```

**Comment by rueian** [comment]
Hi @mbrancato,

v1.0.13 is released!
