### ISSUE TITLE
Ring PutOne panics with unaligned 64-bit on Raspberry PI 4 (arm64)

### ISSUE THREAD

**Issue by xaxa06** [redis/rueidis#407]
Spotted while running GitLab-CE (for which their KAS component is using this Rueidis client) and it keeps streaming this panic error in logs

```bash
2023-11-11_17:52:14.60237 goroutine 67 [running]:
2023-11-11_17:52:14.60243 runtime/internal/atomic.panicUnaligned()
2023-11-11_17:52:14.60247       /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
2023-11-11_17:52:14.60250 runtime/internal/atomic.Xadd64(0x4149354, 0x1)
2023-11-11_17:52:14.60361       /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
2023-11-11_17:52:14.60365 github.com/redis/rueidis.(*ring).PutOne(0x4149320, {0x4012360, 0x3000, 0x8000})
2023-11-11_17:52:14.60372       /root/go/pkg/mod/github.com/redis/rueidis@v1.0.14/ring.go:55 +0x34
2023-11-11_17:52:14.60375 github.com/redis/rueidis.(*pipe).Do(0x3d76820, {0x131c490, 0x3deb560}, {0x4012360, 0x3000, 0x8000})
2023-11-11_17:52:14.60378       /root/go/pkg/mod/github.com/redis/rueidis@v1.0.14/pipe.go:814 +0x2ec
2023-11-11_17:52:14.60387 github.com/redis/rueidis.(*pipe).Receive(0x3d76820, {0x131c490, 0x3deb560}, {0x4012360, 0x3000, 0x8000}, 0x40f0030)
2023-11-11_17:52:14.60390       /root/go/pkg/mod/github.com/redis/rueidis@v1.0.14/pipe.go:687 +0x24c
2023-11-11_17:52:14.60393 github.com/redis/rueidis.(*mux).Receive(0x3d36000, {0x131c490, 0x3deb560}, {0x4012360, 0x3000, 0x8000}, 0x40f0030)
2023-11-11_17:52:14.60396       /root/go/pkg/mod/github.com/redis/rueidis@v1.0.14/mux.go:322 +0xc0
2023-11-11_17:52:14.60399 github.com/redis/rueidis.(*singleClient).Receive(0x3c0f890, {0x131c490, 0x3deb560}, {0x4012360, 0x3000, 0x8000}, 0x40f0030)
2023-11-11_17:52:14.60402       /root/go/pkg/mod/github.com/redis/rueidis@v1.0.14/client.go:107 +0x58
2023-11-11_17:52:14.60405 gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/cmd/kas/kasapp.(*serverApi).subscribeToEvents.func1({0x131c490, 0x3deb560})
2023-11-11_17:52:14.60458       /var/cache/omnibus/src/gitlab-kas/cmd/kas/kasapp/server_api.go:103 +0x170
2023-11-11_17:52:14.60471 gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/internal/tool/retry.PollWithBackoff({0x131c490, 0x3deb560}, {{0x1313ec8, 0x3ef08c0}, 0x2faf080, 0x1, 0x40ee0c0}, 0x3c2ef50)
2023-11-11_17:52:14.60475       /var/cache/omnibus/src/gitlab-kas/internal/tool/retry/retry.go:80 +0x238
2023-11-11_17:52:14.60478 gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/cmd/kas/kasapp.(*serverApi).subscribeToEvents(0x4160b40, {0x131c490, 0x3deb560})
2023-11-11_17:52:14.60481       /var/cache/omnibus/src/gitlab-kas/cmd/kas/kasapp/server_api.go:101 +0x74
2023-11-11_17:52:14.60484 gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/internal/module/notifications/server.(*module).Run(0x3fc1048, {0x131c490, 0x3deb560})
2023-11-11_17:52:14.60487       /var/cache/omnibus/src/gitlab-kas/internal/module/notifications/server/module.go:16 +0x30
2023-11-11_17:52:14.60490 gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/cmd/kas/kasapp.startModules.func1({0x131c490, 0x3deb560})
2023-11-11_17:52:14.60493       /var/cache/omnibus/src/gitlab-kas/cmd/kas/kasapp/configured_app.go:663 +0x3c
2023-11-11_17:52:14.60497 github.com/ash2k/stager.(*stage).Go.func1()
2023-11-11_17:52:14.60500       /root/go/pkg/mod/github.com/ash2k/stager@v0.3.0/stage.go:25 +0x34
2023-11-11_17:52:14.60503 created by github.com/ash2k/stager.(*stage).Go
2023-11-11_17:52:14.60522       /root/go/pkg/mod/github.com/ash2k/stager@v0.3.0/stage.go:24 +0x7c
2023-11-11_17:52:15.74897 panic: unaligned 64-bit atomic operation
```

I reproduce the issue when cloning redis/rueidis and running Ring unit test:

```bash
go test -v -run TestRing

=== RUN   TestRing
=== RUN   TestRing/PutOne
panic: unaligned 64-bit atomic operation

goroutine 38 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x25244b4, 0x1)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/redis/rueidis.(*ring).PutOne(0x2524480, {0x2564588, 0x0, 0x0})
        /home/xavier/go/src/rueidis/ring.go:55 +0x34
created by github.com/redis/rueidis.TestRing.func1 in goroutine 35
        /home/xavier/go/src/rueidis/ring_test.go:24 +0xf8
panic: unaligned 64-bit atomic operation
[...]
```

My hardware is a Raspberry PI 4, running [Raspberry Pi OS (64-bit)](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit), I've installed Go using standard instructions and [go1.21.4.linux-arm64.tar.gz](https://go.dev/dl/go1.21.4.linux-arm64.tar.gz), however for some reason Go sets GOARCH to "arm" (ie, 32bit) instead of "arm64" - see `go env` output below:

Distro:
```
uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```
```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

Go env:
```
go version
go version go1.21.4 linux/arm64
```
```
go env
GO111MODULE=''
GOARCH='arm'
GOBIN=''
GOCACHE='/home/xavier/.cache/go-build'
GOENV='/home/xavier/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/xavier/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/xavier/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
GOARM='7'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='0'
GOMOD='/home/xavier/go/src/rueidis/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -marm -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build2790280466=/tmp/go-build -gno-record-gcc-switches'
```

Googling for it, I found this that may be a clue / starting point: https://github.com/golang/go/issues/23345

**Comment by xaxa06** [comment]
I run a couple more of checks, and for info, reverting the alignment change that was introduced in https://github.com/redis/rueidis/commit/d3b3668edeb0bd038cf2d839170d3d0be1373995 seems to solve it: 

```
diff --git a/ring.go b/ring.go
index f3f92b2..b0b6526 100644
--- a/ring.go
+++ b/ring.go
@@ -31,13 +31,12 @@ func newRing(factor int) *ring {
 }

 type ring struct {
-       store []node // store's size must be 2^N to work with the mask
-       _     [5]uint64
        write uint64
        _     [7]uint64
        read1 uint64
        read2 uint64
        mask  uint64
+       store []node // store's size must be 2^N to work with the mask
 }

 type node struct {
```

```
go test -v -run TestRing
=== RUN   TestRing
=== RUN   TestRing/PutOne
=== RUN   TestRing/PutMulti
=== RUN   TestRing/NextWriteCmd_&_NextResultCh
=== RUN   TestRing/PutOne_Wakeup_WaitForWrite
=== RUN   TestRing/PutMulti_Wakeup_WaitForWrite
--- PASS: TestRing (0.34s)
    --- PASS: TestRing/PutOne (0.07s)
    --- PASS: TestRing/PutMulti (0.06s)
    --- PASS: TestRing/NextWriteCmd_&_NextResultCh (0.00s)
    --- PASS: TestRing/PutOne_Wakeup_WaitForWrite (0.10s)
    --- PASS: TestRing/PutMulti_Wakeup_WaitForWrite (0.10s)
PASS
ok      github.com/redis/rueidis        0.363s
```

**Comment by rueian** [comment]
Hi @xaxa06,

Thank you for finding the bug. While I don't have arm machines, do you find other places that have the same bug?

**Comment by xaxa06** [comment]
From what I was able to tell by running go test on the whole project, the atomic.AddUint64 from lru.Flight() are also panicing similarly, ex: 

```
go test -v .
=== RUN   TestCacheStore
=== RUN   TestCacheStore/LRUCacheStore
=== RUN   TestCacheStore/LRUCacheStore/Flight_and_Update
--- FAIL: TestCacheStore (0.00s)
    --- FAIL: TestCacheStore/LRUCacheStore (0.00s)
        --- FAIL: TestCacheStore/LRUCacheStore/Flight_and_Update (0.00s)
panic: unaligned 64-bit atomic operation [recovered]
        panic: unaligned 64-bit atomic operation

goroutine 25 [running]:
testing.tRunner.func1.2({0x422f00, 0x52eba0})
        /usr/local/go/src/testing/testing.go:1545 +0x27c
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1548 +0x42c
panic({0x422f00, 0x52eba0})
        /usr/local/go/src/runtime/panic.go:914 +0x244
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x1c93234, 0x1)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/redis/rueidis.(*lru).Flight(0x1ca6300, {0x46e6c6, 0x3}, {0x46e6c9, 0x3}, 0x5f5e100, {0xc14c5dcc1f58900a, 0xb4bd7b, 0x765ae0})
        /home/xavier/go/src/rueidis/lru.go:124 +0x76c
github.com/redis/rueidis.test.func1(0x1c9a870)
        /home/xavier/go/src/rueidis/cache_test.go:16 +0xa8
testing.tRunner(0x1c9a870, 0x1c8e4e8)
        /usr/local/go/src/testing/testing.go:1595 +0x124
created by testing.(*T).Run in goroutine 24
        /usr/local/go/src/testing/testing.go:1648 +0x3f0
FAIL    github.com/redis/rueidis        0.020s
FAIL
```

Also seen in these other tests (all with a smiliar call stack up to lru.Flight(..) )
- TestLRU/Cache_Hit_&_Expire
- TestClientSideCaching

At this stage I got lazy and stopped manually skipping KO testst to figure out the next one, instead I assumed it's unlikely some other path has issue and wasn't tested yet by all these tests. 

Also I tried running this ./docker-test.sh, but no luck, looks like some of the images needed by compose do not have arm64 versions:
```
./dockertest.sh

trap "docker compose down -v" EXIT
docker compose up -d
[+] Running 10/51
[...]
no matching manifest for linux/arm/v8 in the manifest list entries
docker compose down -v
```

My environment is still identical to the one I gave in my initial message (see https://github.com/redis/rueidis/issues/407#issue-1989078385)

Let me know if you'd like me to run some more tests or provide complementary info.

**Comment by rueian** [comment]
Hi @xaxa06, I have pushed a fix here https://github.com/redis/rueidis/pull/408. Would you like to test it?

**Comment by xaxa06** [comment]
Hi @rueian, nice! I'll try to test it tonight once at home and revert back to you !

**Comment by xaxa06** [comment]
I confirm with [#408](https://github.com/redis/rueidis/pull/408) all tests are now passing, no more panic :)

```sh
➜  rueidis git:(fix-atomic-alignment) ✗ go test -v .
[...]
--- PASS: TestParseURL (0.00s)
=== RUN   TestMustParseURL
--- PASS: TestMustParseURL (0.00s)
=== RUN   TestMustParseURLUnix
--- PASS: TestMustParseURLUnix (0.00s)
PASS
ok      github.com/redis/rueidis        74.387s
```

(note: I skipped the ones for redis_test.go as I still couldn't get that docker compose redis cluster to work on my env for same reason as I mentioned in my earlier comment, but I doubt there would be any uncaught alignment issue hiding there)

**Comment by rueian** [comment]
it’s OK thank you for your assistance!
